---
apiVersion: v1
kind: Service
metadata:
  name: testapp
  namespace: default
  labels:
    app: testapp
spec:
  type: LoadBalancer
  selector:
    app: testapp
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
