apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testapp
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - image: docker.io/nginx
        name: testapp
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: nginxconfig
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true
        - name: testapp
          mountPath: /var/www/index.html
          readOnly: true
      volumes:
      - name: nginxconfig
        configMap:
          name: nginxconfig
          items:
          - key: default.conf
            path: default.conf
      - name: testapp
        configMap:
          name: testapp
          items:
          - key: index.html
            path: index.html
